## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
# from config import g_key
from config import weather_api_key

# Configure gmaps API key
# gmaps.configure(api_key=g_key)
gmaps.configure(api_key=weather_api_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Weather_Database/WeatherPy_vacation.csv")
vacation_df.head()

City_ID             City Country  Max Temp Current Description      Lat  \
0        7  Bambous Virieux      MU     79.21          light rain -20.3428   
1        9           Noumea      NC     85.98          few clouds -22.2763   
2       12           Atuona      PF     79.54          few clouds  -9.8000   
3       13        Hithadhoo      MV     83.68           clear sky  -0.6000   
4       15          Goundam      ML     80.96     overcast clouds  16.4145   

        Lng        Hotel Name  
0   57.7575  Vieux Grand Port  
1  166.4572            Nouméa  
2 -139.0333            Atuona  
3   73.0833         Addu City  
4   -3.6708           Goundam

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [7]:
vacation_df.head()

City_ID             City Country  Max Temp Current Description      Lat  \
0        7  Bambous Virieux      MU     79.21          light rain -20.3428   
1        9           Noumea      NC     85.98          few clouds -22.2763   
2       12           Atuona      PF     79.54          few clouds  -9.8000   
3       13        Hithadhoo      MV     83.68           clear sky  -0.6000   
4       15          Goundam      ML     80.96     overcast clouds  16.4145   

        Lng        Hotel Name  
0   57.7575  Vieux Grand Port  
1  166.4572            Nouméa  
2 -139.0333            Atuona  
3   73.0833         Addu City  
4   -3.6708           Goundam

In [5]:
# 4a. Add a marker layer for each city to the map.
# max_temp = vacation_df["Max Temp"]
# fig.add_layer(heat_layer)
# heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
#              max_intensity=300, (point_radius=4)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [34]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

## Indonesian Getaway

vacation_start = vacation_df.loc[vacation_df["City"] == "Meulaboh"]
vacation_end = vacation_df.loc[vacation_df["City"] == "meulaboh"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "Padang"]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Kawalu"]
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Boyolangu"] 

In [35]:
import numpy as np

In [36]:
vacation_start

City_ID      City Country  Max Temp Current Description     Lat      Lng  \
117      392  Meulaboh      ID     84.63     overcast clouds  4.1363  96.1285   

    Hotel Name  
117   Meulaboh

In [37]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
# Start Location
loc1 = vacation_start [["Lat", "Lng"]].to_numpy()
start=[]
for i in loc1 :
    for u in i:
        start.append(u)

# End Location
end = start
loc2 = vacation_end[["Lat", "Lng"]].to_numpy()

# First stop
loc3 = vacation_stop1[["Lat", "Lng"]].to_numpy()
stop1 = []
for i in loc3 :
    for u in i :
        stop1.append(u)

# Second stop
loc4 = vacation_stop2[["Lat", "Lng"]].to_numpy()
stop2 = []
for i in loc4 :
    for u in i :  
        stop2.append(u)
# Third stop
loc5 = vacation_stop3[["Lat", "Lng"]].to_numpy()
stop3 = []
for i in loc5 :
    for u in i :  
        stop3.append(u)

    print(start)
    print(end)
    print(loc3)
    print(loc4)
    print(loc5)
   

[4.1363, 96.1285]
[4.1363, 96.1285]
[[ -0.9492 100.3543]]
[[ -7.3817 108.2082]]
[[ -8.1181 111.8935]]


In [38]:
import gmaps.datasets

In [40]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
# Help from https://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#directions-layer

fig = gmaps.figure()
directions_layer = gmaps.directions_layer(start, end, waypoints = [stop1, stop2, stop3], travel_mode = 'DRIVING')
fig.add_layer(directions_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [42]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3, vacation_end],ignore_index=True)
itinerary_df

City_ID       City Country  Max Temp Current Description     Lat       Lng  \
0      392   Meulaboh      ID     84.63     overcast clouds  4.1363   96.1285   
1      616     Padang      ID     87.85    scattered clouds -0.9492  100.3543   
2      318     Kawalu      ID     86.31       broken clouds -7.3817  108.2082   
3      299  Boyolangu      ID     85.51       broken clouds -8.1181  111.8935   

    Hotel Name  
0     Meulaboh  
1       Padang  
2  Tasikmalaya  
3  Tulungagung

In [44]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
itinerary_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [46]:
# 11a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=itinerary_info)
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))